### ISSUE TITLE
have approved AE/WTT,when add Liquidity WTT/AE need to approve again

### ISSUE THREAD

**Issue by barceguo** [aeternity/dex-ui#402]
### What happened?

![image](https://user-images.githubusercontent.com/31126684/178997241-b878ecd3-b665-47a1-b65c-5c21f48f1d5b.png)
![捕获1](https://user-images.githubusercontent.com/31126684/178997373-eac1ea14-0073-46e6-970b-c30c88a1324e.JPG)

### How can we reproduce it?

add Liquidity

### mobile

Desktop

### What browsers are you seeing the problem on?

Chrome

**Comment by kenodressel** [comment]
We have a different model to how we do approvals compared to uniswap. By default we only approve the amount of tokens that you need to perform the current transaction. Meaning when you do a swap with WTT and then provide liquidity for AE / WTT you would need to give allowance for both. At the moment we can do this because our gas is much cheaper compared to ETH and its the more secure route. Does this answer your questions?
